// Run `python -m tests.ui_server` first. Uses a throwaway DB and fake Librus data.
const {chromium,devices}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const URL='http://127.0.0.1:8001', OUT=process.env.SCREENSHOTS||'/tmp';
(async()=>{
 const browser=await chromium.launch({headless:true});
 const errors=[];
 const context=await browser.newContext({viewport:{width:1440,height:960}});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 await page.goto(URL);
 await page.locator('#login-user').fill('zosia.nowak');
 await page.locator('#login-password').fill('incorrect');
 await page.locator('#login-form button[type=submit]').click();
 await page.locator('.form-error:not(:empty)').waitFor();
 await page.locator('#login-password').fill('secret');
 await page.locator('#login-form button[type=submit]').click();
 await page.locator('.lesson').first().waitFor();
 await page.screenshot({path:`${OUT}/dzwonek-desktop-light.png`});
 // Second account through settings.
 await page.getByRole('button',{name:'Konta'}).click();
 await page.getByRole('button',{name:'Dodaj',exact:true}).click();
 await page.locator('#librus-user').fill('antek.nowak');
 await page.locator('#librus-password').fill('secret');
 await page.locator('#profile-form button[type=submit]').click();
 await page.locator('#modal').waitFor({state:'hidden'});
 await page.getByText('Antek',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Ciemny'}).click();
 if(await page.evaluate(()=>document.documentElement.dataset.theme)!=='dark')throw Error('theme not applied');
 await page.screenshot({path:`${OUT}/dzwonek-settings-dark.png`});
 await page.getByRole('button',{name:'Plan',exact:true}).click();
 await page.locator('.lesson').first().waitFor();
 await page.screenshot({path:`${OUT}/dzwonek-desktop-dark.png`});
 await page.getByRole('button',{name:'Kolumny'}).click();
 if(await page.locator('.column').count()!==2)throw Error('comparison columns missing');
 await page.getByRole('button',{name:'Zosia'}).click();
 await page.getByRole('button',{name:'Dzień',exact:true}).click();
 if(await page.locator('.lesson .who').count()!==0)throw Error('filter did not work');
 await page.locator('.lesson').first().click();
 await page.locator('dialog .facts').waitFor();
 await page.getByRole('button',{name:'Zamknij'}).last().click();
 await page.getByRole('button',{name:'Następny tydzień'}).click();
 await page.getByRole('button',{name:'Dziś',exact:true}).click();
 await page.getByRole('button',{name:'Systemowy'}).count();
 // Session survives reload: no second login.
 await page.reload();
 await page.locator('.lesson').first().waitFor();
 const cookie=(await context.cookies()).find(c=>c.name==='dzwonek_session');
 if(!cookie||cookie.expires-Date.now()/1000<399*86400)throw Error('session is not long-lived');

 const phone=await browser.newContext({...devices['iPhone 13'],colorScheme:'dark'});
 await phone.addCookies([cookie]);
 const mobile=await phone.newPage();mobile.on('pageerror',e=>errors.push(e.message));
 await mobile.goto(URL);
 await mobile.locator('.lesson').first().waitFor();
 await mobile.screenshot({path:`${OUT}/dzwonek-mobile-dark.png`,fullPage:true});
 if(await mobile.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('mobile page overflow');
 await mobile.getByRole('button',{name:'Kolumny'}).click();
 if(await mobile.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('mobile comparison overflow');
 await mobile.getByRole('button',{name:'Motyw: Systemowy'}).click();
 await mobile.getByRole('button',{name:'Dzień',exact:true}).click();
 await mobile.screenshot({path:`${OUT}/dzwonek-mobile-light.png`,fullPage:true});
 await mobile.evaluate(()=>navigator.serviceWorker.ready);
 const cached=await mobile.evaluate(async()=>{const c=await caches.open('dzwonek-shell-v3');return (await c.keys()).map(r=>r.url)});
 if(cached.some(u=>u.includes('/api/')))throw Error('API cached');

 await page.getByRole('button',{name:'Wyloguj się'}).click();
 await page.locator('#login-form').waitFor();
 if((await page.request.get(URL+'/api/children')).status()!==401)throw Error('logout did not invalidate session');
 const login=await page.request.post(URL+'/api/login',{headers:{'X-Dzwonek':'1'},data:{username:'obcy.uczen',password:'secret'}});
 if(login.status()!==401)throw Error('foreign Librus account was accepted');
 if(errors.length)throw Error(errors.join('\n'));
 console.log('PASS: Librus login, long session, add account, themes, views, filter, details, mobile, PWA privacy, logout.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
