const { chromium, devices } = require(process.env.PLAYWRIGHT_MODULE || '/tmp/dzwonek-browser/node_modules/playwright');
const fs=require('fs');
(async()=>{
 const browser=await chromium.launch({headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1080}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8000');
 await page.getByRole('heading',{name:'Dobry plan na każdy dzień.'}).waitFor();
 await page.locator('.lesson').first().waitFor();
 await page.screenshot({path:'/tmp/dzwonek-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Obok siebie',exact:true}).click();
 if(await page.locator('.child-column').count()!==3)throw Error('comparison columns missing');
 await page.locator('.lesson').first().click();
 await page.getByRole('button',{name:'Wszystko jasne'}).click();
 await page.getByRole('button',{name:'Dzień',exact:true}).click();
 await page.getByRole('button',{name:'Następny tydzień'}).click();
 await page.getByRole('button',{name:'Dzisiaj',exact:true}).click();
 await page.getByRole('button',{name:'Tydzień',exact:true}).click();
 await page.locator('.profile-card.purple').first().click();
 if(await page.locator('.lesson.green').count()!==0)throw Error('filter did not work');
 await page.locator('.all-card').click();
 await page.getByRole('button',{name:'Moja rodzina'}).click();
 await page.getByRole('button',{name:'Edytuj profil'}).first().click();
 await page.locator('#family-password').fill('invalid');
 await page.getByRole('button',{name:'Zaloguj się',exact:true}).last().click();
 await page.locator('.form-error:not(:empty)').waitFor();
 await page.getByRole('button',{name:'Zamknij',exact:true}).click();
 const mobile=await browser.newPage({...devices['iPhone 13']});
 mobile.on('pageerror',e=>errors.push(e.message));
 await mobile.goto('http://127.0.0.1:8000');
 await mobile.locator('.lesson').first().waitFor();
 await mobile.screenshot({path:'/tmp/dzwonek-mobile.png',fullPage:true});
 if(await mobile.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('mobile page overflow');
 await mobile.getByRole('button',{name:'Obok siebie',exact:true}).click();
 await mobile.screenshot({path:'/tmp/dzwonek-mobile-compare.png',fullPage:true});
 if(await mobile.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('mobile comparison overflow');
 await mobile.getByRole('button',{name:'Na telefonie',exact:true}).click();
 await mobile.getByRole('heading',{name:'Dzwonek na Twoim iPhonie'}).waitFor();
 await mobile.getByRole('button',{name:'Rozumiem'}).click();
 await mobile.evaluate(()=>navigator.serviceWorker.ready);
 const cached=await mobile.evaluate(async()=>{const c=await caches.open('dzwonek-shell-v1');return (await c.keys()).map(r=>r.url)});
 if(cached.some(u=>u.includes('/api/')))throw Error('API cached');
 await mobile.context().setOffline(true);await mobile.reload();
 await mobile.getByRole('alert').waitFor();
 if(errors.length)throw Error(errors.join('\n'));
 console.log('PASS: desktop, mobile, comparison, filters, dates, dialogs, login error, PWA shell, offline privacy.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
